language: ruby
script: bundle exec rake
rvm:
- 1.9.3
- 2.0.0
- ruby-head
- jruby-head
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: c5BWuTsLElYu9vnNUopcKUh+7xT98QmPwza2rcmZI8SV6rsPNE+USyk7dx5faVqw9Ld3oo6ZPDVlK56kF+qzHo/l6QBsDCHHJsS0K3WCBWT/CBjy8coMMLuNUolE+7rIOKGqr4xKhnqjUAsaHhcgMjSwwZraUVctLfMXoO1Orqw=
  gem: redis-sinatra
  on:
    tags: true
    repo: redis-store/redis-sinatra
